version: "3.8"

services:
  router:
    build:
      context: .
      dockerfile: Dockerfile.r9
    container_name: wg-router
    privileged: true
    command: ["/sbin/init"]
    networks:
      wg-net:
        ipv4_address: 172.28.0.10

  client1:
    build:
      context: .
      dockerfile: Dockerfile.r9
    container_name: wg-client1
    privileged: true
    command: ["/sbin/init"]
    networks:
      wg-net:
        ipv4_address: 172.28.0.11

  client2:
    build:
      context: .
      dockerfile: Dockerfile.r9
    container_name: wg-client2
    privileged: true
    command: ["/sbin/init"]
    networks:
      wg-net:
        ipv4_address: 172.28.0.12

networks:
  wg-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
