version: "3.8"

services:
  router:
    image: linuxserver/wireguard
    container_name: router
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=UTC
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=2
      - INTERNAL_SUBNET=10.0.0.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./config/router:/config
    networks:
      wg-net:
        ipv4_address: 172.28.0.10

  client1:
    image: linuxserver/wireguard
    container_name: client1
    depends_on:
      - router
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=UTC
      - PEERS=0
    volumes:
      - ./config/client1:/config
    networks:
      wg-net:
        ipv4_address: 172.28.0.11

  client2:
    image: linuxserver/wireguard
    container_name: client2
    depends_on:
      - router
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=UTC
      - PEERS=0
    volumes:
      - ./config/client2:/config
    networks:
      wg-net:
        ipv4_address: 172.28.0.12

networks:
  wg-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
